name: CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r Titanic_Project/requirements/requirements.txt
    - name: Train and save pipeline
      run: python Titanic_Project/titanic_model/train_pipeline.py
    - uses: actions/upload-artifact@v2
      with:
        name: my-trained-pipeline
        path: Titanic_Project/titanic_model/trained_models/*.pkl
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: Titanic_Project/titanic_model/trained_models
    - name: Install dependencies
      run: pip install -r Titanic_Project/requirements/requirements.txt
    - name: Test with pytest
      run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: Titanic_Project/titanic_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: |
        cd Titanic_Project
        python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: Titanic_Project/dist*.whl
        retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
        path: Titanic_Project/titanic_model_api

    - name: Login to akshay Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        cd Titanic_Project/titanic_model_api
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: docker build . -f Titanic_Project/titanic_model_api/Dockerfile -t $DOCKER_USER/bikeshare_model_api:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: docker push $DOCKER_USER/bikeshare_model_api

    - name: Logout to Docker hub
      run: docker logout
